### ISSUE TITLE
Running current version (8.15.1) still indicates available upgrade

### ISSUE THREAD

**Issue by Generaldraven** [kizniche/Mycodo#1268] opened 2023-01-22 19:13 UTC
STOP right now, and please first look to see if the issue you're about to submit is already an open or recently closed issue at https://github.com/kizniche/Mycodo/issues

Please DO NOT OPEN AN ISSUE:

 - If your Mycodo version is not the latest release version, please update your device before submitting your issue (unless your issue is related to not being able to upgrade). Your problem might already be solved.

 - If your issue has been addressed before. If you have any new information that may aid in solving the issue, post it in the issue that already exists.

If you are going to post a new issue, next read How to Write a Good Bug Report at https://forum.radicaldiy.com/t/how-to-write-a-good-bug-report/71

Please complete as many of the sections below, if applicable, to provide the most information that may help with investigating your issue. Replace the text in brackets with your own text describing the issue. The details requested potentially affect which options to pursue. The small amount of time you spend completing the template will also help those providing assistance by reducing the time required to help you.

### Describe the problem/bug

*[Running most current version, 8.15.1 but setting menu still indicates and upgrade is needed and generates a Error 500: Internal server error on attempting upgrade]*

### Versions:

 - Mycodo Version: *[8.15.1]*
 - Raspberry Pi Version: *[4 model B]*
 - Raspbian OS Version: *[Bullseye]*

### Reproducibility

Please list specific setup details that are involved and the steps to reproduce the behavior:

1. *[Click on Gear menu in upper right corner]*
2. *[Click on Upgrade]*

### Expected behavior

*[System updates and "Upgrade" on gear menu is no longer colored red]*

### Additional context

*[I'm unsure if the software updated properly and is still indicating an available upgrade in error of if the installation was incomplete.  Everything appears to be functioning normally might just as easily be solved when updating to a future release.  I have time so just let me know if/what additional info you need from me to run this down. :)

Full error text and traceback:

Error 500: Internal Server Error
Something bad happened but it's probably not your fault. Letting the developers know about these issues is crucial to supporting Mycodo. Please submit a [new issue on GitHub](https://github.com/kizniche/Mycodo/issues/new?template=problem-bug-report.md) with the following diagnostic information and error traceback (copy the entire traceback):

Version: 8.15.1
Database: 16b28ef31b5b
Model: Raspberry Pi 4 Model B Rev 1.5

Release:
Distributor ID: Raspbian
Description: Raspbian GNU/Linux 11 (bullseye)
Release: 11
Codename: bullseye

Firmware:
b''

Error (Full Traceback):

Traceback (most recent call last):
  File "/var/mycodo-root/env/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/mycodo-root/env/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/mycodo-root/env/lib/python3.9/site-packages/flask_restx/api.py", line 675, in error_router
    return original_handler(e)
  File "/var/mycodo-root/env/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/mycodo-root/env/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/var/mycodo-root/env/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/Heloc/Mycodo/mycodo/mycodo_flask/routes_admin.py", line 534, in admin_upgrade
    current_latest_major_version = current_latest_release.split('.')[0]
AttributeError: 'NoneType' object has no attribute 'split']*

**Comment by kizniche** [comment] 2023-01-22 19:24
Duplicate of #1266

**Closed by kizniche** 2023-01-22 19:24 UTC
