### ISSUE TITLE
Bad Checksum Error When Connecting MH-Z19B via UART - USB 

### ISSUE THREAD

**Issue by latimer288** [kizniche/Mycodo#919] opened 2021-01-06 22:34 UTC
### Describe the problem/bug

I am very new to programming and electronics so this is very much a learning process. i have connected the MH-Z19B via UART - USB utilizing mycodo following direction in Kyle Gabriel's hydroponic automation write-up. It appears to be functioning and the operating system is communicating with the sensor however i cannot receive data back to the Pi 4. when reviewing the logs I see the sensor communicating every 15 secs however the error reads bad checksum. Below I have included an example of the log. i believe that is all the info needed as I assume this is a small issue i am over looking.

Thanks for any assistance. 

,665 - INFO - mycodo.daemon - All activated Custom controllers started
2021-01-06 11:52:41,925 - INFO - mycodo.controllers.controller_widget - Activated in 259.3 ms
2021-01-06 11:52:42,926 - INFO - mycodo.daemon - Mycodo daemon started in 2.557 seconds
2021-01-06 11:52:42,930 - INFO - mycodo.daemon - 41.80 MB RAM in use
2021-01-06 14:02:12,572 - INFO - mycodo.controllers.controller_input_1f7a8450 - Activated in 268.1 ms
2021-01-06 14:02:12,583 - ERROR - mycodo.inputs.mh_z19b_1f7a8450 - Bad checksum
2021-01-06 14:02:19,620 - ERROR - mycodo.inputs.mh_z19b_1f7a8450 - Bad checksum
2021-01-06 14:02:34,561 - ERROR - mycodo.inputs.mh_z19b_1f7a8450 - Bad checksum
2021-01-06 14:02:49,613 - ERROR - mycodo.inputs.mh_z19b_1f7a8450 - Bad checksum
2021-01-06 14:03:04,558 - ERROR - mycodo.inputs.mh_z19b_1f7a8450 - Bad checksum
2021-01-06 14:03:19,602 - ERROR - mycodo.inputs.mh_z19b_1f7a8450 - Bad checksum
2021-01-06 14:03:34,545 - ERROR - mycodo.inputs.mh_z19b_1f7a8450 - Bad checksum
2021-01-06 14:03:49,594 - ERROR - mycodo.inputs.mh_z19b_1f7a8450 - Bad checksum
2021-01-06 14:04:04,637 - ERROR - mycodo.inputs.mh_z19b_1f7a8450 - Bad checksum
2021-01-06 14:04:19,581 - ERROR - mycodo.inputs.mh_z19b_1f7a8450 - Bad checksum
2021-01-06 14:04:34,625 - ERROR - mycodo.inputs.mh_z19b_1f7a8450 - Bad checksum
2021-01-06 14:04:49,568 - ERROR - mycodo.inputs.mh_z19b_1f7a8450 - Bad checksum
2021-01-06 14:05:04,613 - ERROR - mycodo.inputs.mh_z19b_1f7a8450 - Bad checksum
2021-01-06 14:05:19,558 - ERROR - mycodo.inputs.mh_z19b_1f7a8450 - Bad checksum
2021-01-06 14:05:34,606 - ERROR - mycodo.inputs.mh_z19b_1f7a8450 - Bad checksum

**Comment by kizniche** [comment] 2021-01-06 22:44
Duplicate of #918

**Closed by kizniche** 2021-01-06 22:44 UTC
