### ISSUE TITLE
I cannot create live graph(sync)  widget for any input 

### ISSUE THREAD

**Issue by dorasprime** [kizniche/Mycodo#1009] opened 2021-05-22 17:31 UTC
When I tried to create sync. graph widget I am getting an error. Can you help mi? 

I have posted the error below, 

Traceback (most recent call last):
  File "/home/pi/Repositories/indigo/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/Repositories/indigo/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/Repositories/indigo/env/lib/python3.7/site-packages/flask_restx/api.py", line 652, in error_router
    return original_handler(e)
  File "/home/pi/Repositories/indigo/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/Repositories/indigo/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/Repositories/indigo/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/Repositories/indigo/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/Repositories/indigo/env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/Repositories/indigo/mycodo/mycodo_flask/routes_page.py", line 798, in page_dashboard
    form_dashboard=form_dashboard)
  File "/home/pi/Repositories/indigo/env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/pi/Repositories/indigo/env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/pi/Repositories/indigo/env/lib/python3.7/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/pi/Repositories/indigo/env/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/pi/Repositories/indigo/mycodo/mycodo_flask/templates/pages/dashboard.html", line 3, in top-level template code
    {% set help_page = ["https://kizniche.github.io/Mycodo/Data-Viewing/#dashboard", dict_translation['dashboard']['title']] %}
  File "/home/pi/Repositories/indigo/mycodo/mycodo_flask/templates/layout.html", line 327, in top-level template code
    {%- block body %}{% endblock -%}
  File "/home/pi/Repositories/indigo/mycodo/mycodo_flask/templates/pages/dashboard.html", line 372, in block 'body'
    {% include 'user_templates/{}'.format(file_js_ready_end) %}
  File "/home/pi/Repositories/indigo/mycodo/mycodo_flask/templates/user_templates/widget_template_widget_graph_synchronous_js_ready_end.html", line 150, in top-level template code
    {%- if 'custom_axis_id' in dict_measurements[each_axis_meas] -%}
jinja2.exceptions.UndefinedError: 'collections.OrderedDict object' has no attribute 'MB'

**Comment by kizniche** [comment] 2021-05-22 17:47
Hi. This is a duplicate of #1001 and has been fixed. It will be available in the next release, unless you upgrade to master (link in the original issue).

**Comment by dorasprime** [comment] 2021-05-22 18:18
Thank you

**Closed** 2021-06-05 16:32 UTC
Labels: duplicate
