### ISSUE TITLE
atlas ph orp wrong values

### ISSUE THREAD

**Issue by ddralle** [kizniche/Mycodo#862] opened 2020-10-05 07:05 UTC
Hello,
I've been tinkering for a few days now and unfortunately I can't get any further.

I use the ORP and PH interfaces from ATLAS via I2C.
Devices are found and can be controlled.

the values of the PH probe cannot be calibrated, totally wrong values come out when calibrating.

if you ventilate the temperature massively, you can influence the value, i think that's a mistake.

I have already exchanged the measuring probes, without success.

the same problem with the REDOX probe, totally wrong values.

self test, different hardware with ATLAS IOT, perfect values.

I already connected a 1WIRE temperature probe to test it, which also does not lead to success.

With the atlas IOT software, I noticed that the order of the 3 point calibration is different, maybe that's because of that
-> mycodo 4,7,10
-> atlas 7,4,10

what can be the reason?

**Comment by kizniche** [comment] 2020-10-05 14:55
duplicate of #861

**Closed by kizniche** 2020-10-05 14:55 UTC
Labels: duplicate
