### ISSUE TITLE
Input type cast error when calibrating Atlas PH

### ISSUE THREAD

**Issue by Hazmit** [kizniche/Mycodo#1038] opened 2021-06-23 03:13 UTC
### Describe the problem/bug

When performing the calibration process on a new Atlas PH sensor I am receiving an error when entering the temperature of the first solution. It appears to be a type cast problem where the code is saving the value as a str and not formatting it properly. I've tried both using a float and integer value. This hard stops you from being able to perform a calibration.

### Versions:

 - Mycodo Version: 8.11.0
 - Raspberry Pi Version: 3B+
 - Raspbian OS Version: Buster Lite fresh install apt-get updated

### Reproducibility

Please list specific setup details that are involved and the steps to reproduce the behavior:

Perform PH calibration for atlas sensor, input temperature, see error on submit.

### Expected behavior

Expected that it will accept the value and continue with calibration.

### Screenshots

Attached
<img width="1203" alt="Screen Shot 2021-06-22 at 7 06 44 PM" src="https://user-images.githubusercontent.com/488993/123029634-e6258480-d38d-11eb-833b-fbd891645427.png">

**Comment by kizniche** [comment] 2021-06-23 03:14
Duplicate of #1022

**Closed by kizniche** 2021-06-23 03:14 UTC

**Comment by Hazmit** [comment] 2021-06-23 04:00
Thanks for marking this so quickly!
Since you marked it I referenced the original bug and was able to calibrate on the input screen! Seems to be a good work around. I see that the other calibration will be removed soon. Appreciate the eyes on the bug report. I owe you a beer.
