### ISSUE TITLE
Mycodo Installation Error - Could not connect to local host

### ISSUE THREAD

**Issue by cedcmoi** [kizniche/Mycodo#1152] opened 2022-02-13 03:54 UTC
Hi,

I'm having trouble installing Mycodo on my RPi 4.
At the end of the installation process, I'm getting the error message "Could not connect to local host. Retrying in 60 seconds"

I've updated every package (apt update && apt upgrade) before installing Mycodo.

I also read an issue (Issue 614[](https://github.com/kizniche/mycodo/issues/614) ) concerning the same problem on github and reproduced the suggestions written on the thread. Still unable to install Mycodo.

I've also flashed my SD card et reinstall Rasbian OS. Still get the same error message

My setup is:
-RPi 4 Running Raspberry Pi OS 64 bit

Here are the last 50 lines from the Mycodo frontend web log can be viewed with the command:
pi@raspberrypi:~ $ journalctl -u mycodoflask | tail -n 50
-- Journal begins at Thu 2022-01-27 22:21:52 EST, ends at Sat 2022-02-12 22:44:00 EST. --
Feb 12 22:11:19 raspberrypi systemd[1]: Started gunicorn daemon for Mycodo flask web user interface.
Feb 12 22:11:19 raspberrypi systemd[5608]: mycodoflask.service: Failed to locate executable /var/mycodo-root/env/bin/gunicorn: No such file or directory
Feb 12 22:11:19 raspberrypi systemd[5608]: mycodoflask.service: Failed at step EXEC spawning /var/mycodo-root/env/bin/gunicorn: No such file or directory
Feb 12 22:11:19 raspberrypi systemd[1]: mycodoflask.service: Main process exited, code=exited, status=203/EXEC
Feb 12 22:11:19 raspberrypi systemd[1]: mycodoflask.service: Failed with result 'exit-code'.
Feb 12 22:40:00 raspberrypi systemd[1]: Started gunicorn daemon for Mycodo flask web user interface.
Feb 12 22:40:00 raspberrypi systemd[7524]: mycodoflask.service: Failed to locate executable /var/mycodo-root/env/bin/gunicorn: No such file or directory
Feb 12 22:40:00 raspberrypi systemd[7524]: mycodoflask.service: Failed at step EXEC spawning /var/mycodo-root/env/bin/gunicorn: No such file or directory
Feb 12 22:40:00 raspberrypi systemd[1]: mycodoflask.service: Main process exited, code=exited, status=203/EXEC
Feb 12 22:40:00 raspberrypi systemd[1]: mycodoflask.service: Failed with result 'exit-code'.

Thanks !

**Comment by kizniche** [comment] 2022-02-13 03:56
Duplicate of #1149

**Closed by kizniche** 2022-02-13 03:56 UTC
