### ISSUE TITLE
Install keeps failing on brand new Raspberry Pi 4

### ISSUE THREAD

**Issue by griffira** [kizniche/Mycodo#833] opened 2020-09-02 20:47 UTC
Hello,

I continue to have problems with the install. I even re-imaged my SD card to ensure I was starting out fresh then, tried to install Mycodo immediately thereafter, to no avail. If it means anything, I remember the "ModuleNotFoundError: No module named 'setuptools._distutils'" error coming up before on the install attempts before I wiped the SD card.

Thanks in advance for any help...I've got a brand new Atlas pH probe kit I'm itching to play with ;-)

From the setup log at the first sign of trouble:

Collecting bcrypt==3.1.7
  Downloading bcrypt-3.1.7.tar.gz (42 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
ERROR: Exception:
Traceback (most recent call last):
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    status = self.run(options, args)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 325, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 483, in prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 91, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 38, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 96, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 161, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 265, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 86, in _build_backend
    obj = import_module(mod_path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 6, in <module>
    import distutils.core
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/_distutils_hack/__init__.py", line 83, in create_module
    return importlib.import_module('setuptools._distutils')
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'setuptools._distutils'

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pylibftdi==0.19.0
  Downloading pylibftdi-0.19.0-py2.py3-none-any.whl (32 kB)
Requirement already up-to-date: RPi.GPIO in /usr/lib/python3/dist-packages (from -r /home/pi/Mycodo/install/requirements-rpi.txt (line 3)) (0.7.0)
Collecting smbus2==0.3.0
  Downloading https://www.piwheels.org/simple/smbus2/smbus2-0.3.0-py2.py3-none-any.whl (9.1 kB)
Installing collected packages: pylibftdi, smbus2
Successfully installed pylibftdi-0.19.0 smbus2-0.3.0
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting testfixtures==6.14.1
  Downloading testfixtures-6.14.1-py2.py3-none-any.whl (89 kB)
Collecting mock==4.0.2
  Downloading mock-4.0.2-py3-none-any.whl (28 kB)
Collecting pytest==5.4.3
  Downloading pytest-5.4.3-py3-none-any.whl (248 kB)
Collecting factory_boy==2.12.0
  Downloading factory_boy-2.12.0-py2.py3-none-any.whl (36 kB)
Collecting webtest==2.0.35
  Downloading WebTest-2.0.35-py2.py3-none-any.whl (32 kB)
Collecting pluggy<1.0,>=0.12
  Downloading pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting attrs>=17.4.0
  Downloading attrs-20.1.0-py2.py3-none-any.whl (49 kB)
Collecting more-itertools>=4.0.0
  Downloading more_itertools-8.5.0-py3-none-any.whl (44 kB)
Collecting packaging
  Downloading packaging-20.4-py2.py3-none-any.whl (37 kB)
Requirement already satisfied, skipping upgrade: importlib-metadata>=0.12; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from pytest==5.4.3->-r /home/pi/Mycodo/install/requirements-testing.txt (line 4)) (1.7.0)
Collecting wcwidth
  Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting py>=1.5.0
  Downloading py-1.9.0-py2.py3-none-any.whl (99 kB)
Collecting Faker>=0.7.0
  Downloading Faker-4.1.2-py3-none-any.whl (1.0 MB)
Collecting WebOb>=1.2
  Downloading WebOb-1.8.6-py2.py3-none-any.whl (114 kB)
Collecting waitress>=0.8.5
  Downloading waitress-1.4.4-py2.py3-none-any.whl (58 kB)
Requirement already satisfied, skipping upgrade: six in /usr/lib/python3/dist-packages (from webtest==2.0.35->-r /home/pi/Mycodo/install/requirements-testing.txt (line 6)) (1.12.0)
Requirement already satisfied, skipping upgrade: beautifulsoup4 in /usr/lib/python3/dist-packages (from webtest==2.0.35->-r /home/pi/Mycodo/install/requirements-testing.txt (line 6)) (4.7.1)
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest==5.4.3->-r /home/pi/Mycodo/install/requirements-testing.txt (line 4)) (3.1.0)
Collecting python-dateutil>=2.4
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting text-unidecode==1.3
  Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Installing collected packages: testfixtures, mock, pluggy, attrs, more-itertools, pyparsing, packaging, wcwidth, py, pytest, python-dateutil, text-unidecode, Faker, factory-boy, WebOb, waitress, webtest
Successfully installed Faker-4.1.2 WebOb-1.8.6 attrs-20.1.0 factory-boy-2.12.0 mock-4.0.2 more-itertools-8.5.0 packaging-20.4 pluggy-0.13.1 py-1.9.0 pyparsing-2.4.7 pytest-5.4.3 python-dateutil-2.8.1 testfixtures-6.14.1 text-unidecode-1.3 waitress-1.4.4 wcwidth-0.2.5 webtest-2.0.35
--2020-09-02 15:17:41--  https://project-downloads.drogon.net/wiringpi-latest.deb
Resolving project-downloads.drogon.net (project-downloads.drogon.net)... 188.246.205.22, 2a03:9800:10:7b::2
Connecting to project-downloads.drogon.net (project-downloads.drogon.net)|188.246.205.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 52260 (51K) [application/x-debian-package]
Saving to: ‘wiringpi-latest.deb’

     0K .......... .......... .......... .......... .......... 97%  201K 0s
    50K .                                                     100% 1974G=0.2s

2020-09-02 15:17:42 (205 KB/s) - ‘wiringpi-latest.deb’ saved [52260/52260]

(Reading database ... 93509 files and directories currently installed.)
Preparing to unpack wiringpi-latest.deb ...
Unpacking wiringpi (2.52) over (2.50) ...
Setting up wiringpi (2.52) ...
Processing triggers for man-db (2.8.5-2) ...

#### Incorrect InfluxDB version (v(none)) installed. Installing v1.8.0-1...
Selecting previously unselected package influxdb.
(Reading database ... 93509 files and directories currently installed.)
Preparing to unpack influxdb_1.8.0_armhf.deb ...
Unpacking influxdb (1.8.0-1) ...
Setting up influxdb (1.8.0-1) ...
Created symlink /etc/systemd/system/influxd.service → /lib/systemd/system/influxdb.service.
Created symlink /etc/systemd/system/multi-user.target.wants/influxdb.service → /lib/systemd/system/influxdb.service.
Processing triggers for man-db (2.8.5-2) ...

#### Creating mycodo user
Adding user `mycodo' to group `adm' ...
Adding user mycodo to group adm
Done.
Adding user `mycodo' to group `dialout' ...
Adding user mycodo to group dialout
Done.
Adding user `mycodo' to group `gpio' ...
Adding user mycodo to group gpio
Done.
Adding user `mycodo' to group `i2c' ...
Adding user mycodo to group i2c
Done.
Adding user `mycodo' to group `kmem' ...
Adding user mycodo to group kmem
Done.
Adding user `mycodo' to group `video' ...
Adding user mycodo to group video
Done.
Adding user `pi' to group `mycodo' ...
Adding user pi to group mycodo
Done.
Adding user `mycodo' to group `pi' ...
Adding user mycodo to group pi
Done.

#### Compiling mycodo_wrapper
/home/pi/Mycodo/mycodo/scripts/mycodo_wrapper.c: In function ‘upgrade_commands’:
/home/pi/Mycodo/mycodo/scripts/mycodo_wrapper.c:17:5: warning: ‘strncat’ specified bound 255 equals destination size [-Wstringop-overflow=]
     strncat(full_cmd, "/upgrade_commands.sh ", sizeof(full_cmd));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/Mycodo/mycodo/scripts/mycodo_wrapper.c: In function ‘main’:
/home/pi/Mycodo/mycodo/scripts/mycodo_wrapper.c:35:4: warning: ‘strncat’ specified bound 255 equals destination size [-Wstringop-overflow=]
    strncat(restoreScript, "/upgrade_commands.sh backup-create", sizeof(restoreScript));
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#### Installing logrotate scripts
logrotate execution moved from cron.daily to cron.hourly
Mycodo logrotate script installed

#### Generating SSL certificates at /home/pi/Mycodo/mycodo/mycodo_flask/ssl_certs (replace with your own if desired)
Generating RSA private key, 4096 bit long modulus (2 primes)
...........................++++
............................................++++
e is 65537 (0x010001)
writing RSA key
Signature ok
subject=O = mycodo, OU = mycodo, CN = mycodo
Getting Private key

#### Disabling installed mycodo startup script
Failed to disable unit: Unit file mycodo.service does not exist.
#### Enabling current mycodo startup script
Created symlink /etc/systemd/system/mycodo.service → /home/pi/Mycodo/install/mycodo.service.
Created symlink /etc/systemd/system/multi-user.target.wants/mycodo.service → /home/pi/Mycodo/install/mycodo.service.

#### Compiling Translations
/home/pi/Mycodo/mycodo/scripts/upgrade_commands.sh: line 115: /home/pi/Mycodo/env/bin/pybabel: No such file or directory

#### Generating widget HTML files
Traceback (most recent call last):
  File "/home/pi/Mycodo/mycodo/mycodo_client.py", line 31, in <module>
    import Pyro5.errors
ModuleNotFoundError: No module named 'Pyro5'

#### Updating Mycodo restart monitor crontab entry
Crontab entry does not exist, nothing to do.
no crontab for root
Appending to crontab:
-----------------------------------------------
@reboot /var/mycodo-root/env/bin/python /var/mycodo-root/mycodo/scripts/restart_daemon.py --continuouscheck &
-----------------------------------------------
To remove previously added crontab entry, run: /home/pi/Mycodo/install/crontab.sh restart_daemon --remove

#### Creating mycodo user
useradd: user 'mycodo' already exists
The user `mycodo' is already a member of `adm'.
The user `mycodo' is already a member of `dialout'.
The user `mycodo' is already a member of `gpio'.
The user `mycodo' is already a member of `i2c'.
The user `mycodo' is already a member of `kmem'.
The user `mycodo' is already a member of `video'.
The user `pi' is already a member of `mycodo'.
The user `mycodo' is already a member of `pi'.

#### Compiling mycodo_wrapper
/home/pi/Mycodo/mycodo/scripts/mycodo_wrapper.c: In function ‘upgrade_commands’:
/home/pi/Mycodo/mycodo/scripts/mycodo_wrapper.c:17:5: warning: ‘strncat’ specified bound 255 equals destination size [-Wstringop-overflow=]
     strncat(full_cmd, "/upgrade_commands.sh ", sizeof(full_cmd));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/Mycodo/mycodo/scripts/mycodo_wrapper.c: In function ‘main’:
/home/pi/Mycodo/mycodo/scripts/mycodo_wrapper.c:35:4: warning: ‘strncat’ specified bound 255 equals destination size [-Wstringop-overflow=]
    strncat(restoreScript, "/upgrade_commands.sh backup-create", sizeof(restoreScript));
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#### Installing and configuring nginx web server
Failed to disable unit: Unit file mycodoflask.service does not exist.
Synchronizing state of nginx.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable nginx
Created symlink /etc/systemd/system/multi-user.target.wants/mycodoflask.service → /home/pi/Mycodo/install/mycodoflask.service.
Created symlink /etc/systemd/system/mycodoflask.service → /home/pi/Mycodo/install/mycodoflask.service.

#### Trying again...

ALSO:

pi@raspberrypi:~ $ sudo journalctl -u mycodoflask | tail -n 50
-- Logs begin at Thu 2019-02-14 04:11:59 CST, end at Wed 2020-09-02 15:23:08 CDT. --
Sep 02 15:20:15 raspberrypi systemd[1]: Started gunicorn daemon for Mycodo flask web user interface.
Sep 02 15:20:15 raspberrypi systemd[3939]: mycodoflask.service: Failed to execute command: No such file or directory
Sep 02 15:20:15 raspberrypi systemd[3939]: mycodoflask.service: Failed at step EXEC spawning /var/mycodo-root/env/bin/gunicorn: No such file or directory
Sep 02 15:20:15 raspberrypi systemd[1]: mycodoflask.service: Main process exited, code=exited, status=203/EXEC
Sep 02 15:20:15 raspberrypi systemd[1]: mycodoflask.service: Failed with result 'exit-code'.

**Comment by kizniche** [comment] 2020-09-02 21:05
Duplicate of #832

**Closed** 2020-09-02 21:05 UTC
Labels: duplicate

**Comment by kizniche** [comment] 2020-09-02 21:17
I just posted in the original issue a workaround that will allow the install to complete.
