### ISSUE TITLE
Error 502: Bad Gateway Error

### ISSUE THREAD

**Issue by eliaskill** [kizniche/Mycodo#794] opened 2020-07-21 22:39 UTC
Something bad happened but it's probably not your fault. Try refreshing the page to see if it will load. If that doesn't work, try rebooting your system, then try refreshing it again. If that still doesn't work, submit a new issue on GitHub with any usefull information that can help determine the cause of this issue.

**Comment by kizniche** [comment] 2020-07-22 00:08
Can you execute the command ```journalctl -u mycodoflask | tail -n 60``` and copy the output here?

**Comment by eliaskill** [comment] 2020-07-22 00:13
pi@raspberrypi:~ $ journalctl -u mycodoflask | tail -n 60
-- Logs begin at Tue 2020-07-21 19:48:50 -03, end at Tue 2020-07-21 21:12:13 -03. --
jul 21 20:01:01 raspberrypi systemd[1]: Started gunicorn daemon for Mycodo flask web user interface.
jul 21 20:01:01 raspberrypi systemd[2117]: mycodoflask.service: Failed to execute command: No such file or directory
jul 21 20:01:01 raspberrypi systemd[2117]: mycodoflask.service: Failed at step EXEC spawning /var/mycodo-root/env/bin/gunicorn: No such file or directory
jul 21 20:01:01 raspberrypi systemd[1]: mycodoflask.service: Main process exited, code=exited, status=203/EXEC
jul 21 20:01:01 raspberrypi systemd[1]: mycodoflask.service: Failed with result 'exit-code'.

**Comment by kizniche** [comment] 2020-07-22 00:28
What is the output of these commands?

```bash
cd ~/Mycodo/mycodo
sudo /var/mycodo-root/env/bin/gunicorn \
--workers 1 \
--worker-class gthread \
--threads 2 \
--timeout 300 \
--pid /var/run/mycodoflask.pid \
--bind unix:/var/run/mycodoflask.sock start_flask_ui:app
```

**Comment by eliaskill** [comment] 2020-07-22 00:30
pi@raspberrypi:~ $ cd ~/Mycodo/mycodo
pi@raspberrypi:~/Mycodo/mycodo $ sudo /var/mycodo-root/env/bin/gunicorn \
> --workers 1 \
> --worker-class gthread \
> --threads 2 \
> --timeout 300 \
> --pid /var/run/mycodoflask.pid \
> --bind unix:/var/run/mycodoflask.sock start_flask_ui:app
sudo: /var/mycodo-root/env/bin/gunicorn: comando não encontrado

**Comment by kizniche** [comment] 2020-07-22 00:40
There seems to be something critically wrong with your install. Did you just install Mycodo? if so, can you attach the setup.log located in ~/Mycodo/install/ ?

**Comment by eliaskill** [comment] 2020-07-22 00:43
### Mycodo installation initiated ter jul 21 19:55:49 -03 2020
#### Mycodo installation began ter jul 21 19:56:36 -03 2020

#### Checking if swap size is 100 MB and needs to be changed to 512 MB
#### Swap not currently set to 100 MB. Not changing.

#### Updating apt repositories
Atingido:1 http://archive.raspberrypi.org/debian buster InRelease
Atingido:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Atingido:3 https://download.sublimetext.com apt/stable/ InRelease
Lendo listas de pacotes...

#### Uninstalling apt version of pip (if installed)
Lendo listas de pacotes...
Construindo árvore de dependências...
Lendo informação de estado...
O pacote 'python-pip' não está instalado, por isso não será removido
Os seguintes pacotes foram instalados automaticamente e já não são necessários:
  libjs-sphinxdoc libjs-underscore libmicrodns0 libpython-all-dev python-all
  python-all-dev python-configparser python-dbus python-entrypoints
  python-keyring python-keyrings.alt python-secretstorage python-wheel
  python-xdg rpi-eeprom-images
Utilize 'sudo apt autoremove' para os remover.
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 16 não atualizados.

#### Installing prerequisite apt packages and update pip
Lendo listas de pacotes...
Construindo árvore de dependências...
Lendo informação de estado...
O pacote 'apache2' não está instalado, por isso não será removido
Os seguintes pacotes foram instalados automaticamente e já não são necessários:
  libjs-sphinxdoc libjs-underscore libmicrodns0 libpython-all-dev python-all
  python-all-dev python-configparser python-dbus python-entrypoints
  python-keyring python-keyrings.alt python-secretstorage python-wheel
  python-xdg rpi-eeprom-images
Utilize 'sudo apt autoremove' para os remover.
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 16 não atualizados.
Lendo listas de pacotes...
Construindo árvore de dependências...
Lendo informação de estado...
gawk is already the newest version (1:4.2.1+dfsg-1).
gcc is already the newest version (4:8.3.0-1+rpi2).
git is already the newest version (1:2.20.1-2+deb10u3).
libffi-dev is already the newest version (3.2.1-9).
libi2c-dev is already the newest version (4.1-1).
logrotate is already the newest version (3.14.0-4).
moreutils is already the newest version (0.62-1+b1).
nginx is already the newest version (1.14.2-2+deb10u1).
python3 is already the newest version (3.7.3-1).
python3-dev is already the newest version (3.7.3-1).
python3-pylint-common is already the newest version (0.2.5-2).
python3-setuptools is already the newest version (40.8.0-1).
python3-smbus is already the newest version (4.1-1).
rng-tools is already the newest version (2-unofficial-mt.14-1).
sqlite3 is already the newest version (3.27.2-3).
wget is already the newest version (1.20.1-1.1).
Os seguintes pacotes foram instalados automaticamente e já não são necessários:
  libjs-sphinxdoc libjs-underscore libmicrodns0 libpython-all-dev python-all
  python-all-dev python-configparser python-dbus python-entrypoints
  python-keyring python-keyrings.alt python-secretstorage python-wheel
  python-xdg rpi-eeprom-images
Utilize 'sudo apt autoremove' para os remover.
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 16 não atualizados.
Searching for pip
Best match: pip 20.1.1
Adding pip 20.1.1 to easy-install.pth file
Installing pip script to /usr/local/bin
Installing pip3 script to /usr/local/bin
Installing pip3.8 script to /usr/local/bin

Using /usr/local/lib/python3.7/dist-packages
Processing dependencies for pip
Finished processing dependencies for pip
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already up-to-date: pip in /usr/local/lib/python3.7/dist-packages (20.1.1)

#### Checking python 3 virtualenv
#### Virtualenv doesn't exist. Creating...
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already up-to-date: virtualenv in /usr/local/lib/python3.7/dist-packages (20.0.27)
Requirement already satisfied, skipping upgrade: importlib-metadata<2,>=0.12; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from virtualenv) (1.7.0)
Requirement already satisfied, skipping upgrade: filelock<4,>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from virtualenv) (3.0.12)
Requirement already satisfied, skipping upgrade: appdirs<2,>=1.4.3 in /usr/local/lib/python3.7/dist-packages (from virtualenv) (1.4.4)
Requirement already satisfied, skipping upgrade: six<2,>=1.9.0 in /usr/lib/python3/dist-packages (from virtualenv) (1.12.0)
Requirement already satisfied, skipping upgrade: distlib<1,>=0.3.1 in /usr/local/lib/python3.7/dist-packages (from virtualenv) (0.3.1)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata<2,>=0.12; python_version < "3.8"->virtualenv) (3.1.0)
created virtual environment CPython3.7.3.final.0-32 in 6438ms
  creator CPython3Posix(dest=/home/pi/Mycodo/env, clear=False, global=True)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==20.1.1, setuptools==49.2.0, wheel==0.34.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

#### Updating pip
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already up-to-date: pip in ./env/lib/python3.7/site-packages (20.1.1)

#### Installing pip requirements
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already up-to-date: pip in ./env/lib/python3.7/site-packages (20.1.1)
Requirement already up-to-date: setuptools in ./env/lib/python3.7/site-packages (49.2.0)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting alembic==1.4.1
  Using cached https://www.piwheels.org/simple/alembic/alembic-1.4.1-py2.py3-none-any.whl (160 kB)
Collecting argparse==1.4.0
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting bcrypt==3.1.7
  Using cached bcrypt-3.1.7.tar.gz (42 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /home/pi/Mycodo/env/bin/python /home/pi/Mycodo/env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpnlwuj70e
         cwd: /tmp/pip-install-3gmtg3oe/bcrypt
    Complete output (34 lines):
    Traceback (most recent call last):
      File "/home/pi/Mycodo/env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/home/pi/Mycodo/env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/pi/Mycodo/env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 140, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 126, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 240, in <module>
        **keywords_with_side_effects(sys.argv)
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 447, in __init__
        k: v for k, v in attrs.items()
      File "/usr/lib/python3.7/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 739, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-env-4kukyut2/overlay/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 217, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/tmp/pip-build-env-4kukyut2/overlay/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/tmp/pip-build-env-4kukyut2/overlay/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "src/build_bcrypt.py", line 21, in <module>
        ffi = FFI()
      File "/tmp/pip-build-env-4kukyut2/overlay/lib/python3.7/site-packages/cffi/api.py", line 56, in __init__
        backend.__version__, backend.__file__))
    Exception: Version mismatch: this is the 'cffi' package version 1.14.0, located in '/tmp/pip-build-env-4kukyut2/overlay/lib/python3.7/site-packages/cffi/api.py'.  When we import the top-level '_cffi_backend' extension module, we get version 1.12.2, located in '/usr/lib/python3/dist-packages/_cffi_backend.cpython-37m-arm-linux-gnueabihf.so'.  The two versions should be equal; check your installation.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/pi/Mycodo/env/bin/python /home/pi/Mycodo/env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpnlwuj70e Check the logs for full command output.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pylibftdi==0.18.1
  Using cached https://www.piwheels.org/simple/pylibftdi/pylibftdi-0.18.1-py2.py3-none-any.whl (32 kB)
Requirement already up-to-date: RPi.GPIO in /usr/lib/python3/dist-packages (from -r /home/pi/Mycodo/install/requirements-rpi.txt (line 3)) (0.7.0)
Collecting smbus2==0.3.0
  Using cached https://www.piwheels.org/simple/smbus2/smbus2-0.3.0-py2.py3-none-any.whl (9.1 kB)
Installing collected packages: pylibftdi, smbus2
Successfully installed pylibftdi-0.18.1 smbus2-0.3.0
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting testfixtures==6.14.1
  Using cached testfixtures-6.14.1-py2.py3-none-any.whl (89 kB)
Collecting mock==4.0.2
  Using cached mock-4.0.2-py3-none-any.whl (28 kB)
Collecting pytest==5.4.3
  Using cached pytest-5.4.3-py3-none-any.whl (248 kB)
Collecting factory_boy==2.12.0
  Using cached factory_boy-2.12.0-py2.py3-none-any.whl (36 kB)
Collecting webtest==2.0.35
  Using cached WebTest-2.0.35-py2.py3-none-any.whl (32 kB)
Collecting py>=1.5.0
  Using cached py-1.9.0-py2.py3-none-any.whl (99 kB)
Collecting wcwidth
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Requirement already satisfied, skipping upgrade: importlib-metadata>=0.12; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from pytest==5.4.3->-r /home/pi/Mycodo/install/requirements-testing.txt (line 4)) (1.7.0)
Collecting pluggy<1.0,>=0.12
  Using cached pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting attrs>=17.4.0
  Using cached attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting packaging
  Using cached packaging-20.4-py2.py3-none-any.whl (37 kB)
Collecting more-itertools>=4.0.0
  Using cached more_itertools-8.4.0-py3-none-any.whl (43 kB)
Collecting Faker>=0.7.0
  Using cached Faker-4.1.1-py3-none-any.whl (1.0 MB)
Collecting WebOb>=1.2
  Using cached WebOb-1.8.6-py2.py3-none-any.whl (114 kB)
Requirement already satisfied, skipping upgrade: beautifulsoup4 in /usr/lib/python3/dist-packages (from webtest==2.0.35->-r /home/pi/Mycodo/install/requirements-testing.txt (line 6)) (4.7.1)
Collecting waitress>=0.8.5
  Using cached waitress-1.4.4-py2.py3-none-any.whl (58 kB)
Requirement already satisfied, skipping upgrade: six in /usr/lib/python3/dist-packages (from webtest==2.0.35->-r /home/pi/Mycodo/install/requirements-testing.txt (line 6)) (1.12.0)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest==5.4.3->-r /home/pi/Mycodo/install/requirements-testing.txt (line 4)) (3.1.0)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting python-dateutil>=2.4
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting text-unidecode==1.3
  Using cached text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Installing collected packages: testfixtures, mock, py, wcwidth, pluggy, attrs, pyparsing, packaging, more-itertools, pytest, python-dateutil, text-unidecode, Faker, factory-boy, WebOb, waitress, webtest
Successfully installed Faker-4.1.1 WebOb-1.8.6 attrs-19.3.0 factory-boy-2.12.0 mock-4.0.2 more-itertools-8.4.0 packaging-20.4 pluggy-0.13.1 py-1.9.0 pyparsing-2.4.7 pytest-5.4.3 python-dateutil-2.8.1 testfixtures-6.14.1 text-unidecode-1.3 waitress-1.4.4 wcwidth-0.2.5 webtest-2.0.35
--2020-07-21 19:58:46--  https://project-downloads.drogon.net/wiringpi-latest.deb
Resolvendo project-downloads.drogon.net (project-downloads.drogon.net)... 188.246.205.22, 2a03:9800:10:7b::2
Conectando-se a project-downloads.drogon.net (project-downloads.drogon.net)|188.246.205.22|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 200 OK
Tamanho: 52260 (51K) [application/x-debian-package]
Salvando em: “wiringpi-latest.deb”

     0K .......... .......... .......... .......... .......... 97%  132K 0s
    50K .                                                     100% 1974G=0,4s

2020-07-21 19:58:48 (134 KB/s) - “wiringpi-latest.deb” salvo [52260/52260]

(Lendo banco de dados ... 99104 ficheiros e directórios actualmente instalados.)
A preparar para desempacotar wiringpi-latest.deb ...
A descompactar wiringpi (2.52) sobre (2.52) ...
Configurando wiringpi (2.52) ...
A processar 'triggers' para man-db (2.8.5-2) ...

#### Ensuring compatible version of influxdb is installed ####
#### Incorrect InfluxDB version (v) installed. Installing v1.8.0-1...
(Lendo banco de dados ... 99104 ficheiros e directórios actualmente instalados.)
A preparar para desempacotar influxdb_1.8.0_armhf.deb ...
A descompactar influxdb (1.8.0-1) sobre (1.8.0-1) ...
Configurando influxdb (1.8.0-1) ...
A processar 'triggers' para man-db (2.8.5-2) ...

#### Creating InfluxDB database and user
#### Attempting to connect...
#### Could not connect to Influxdb. Waiting 30 seconds then trying again...
#### Attempting to connect...
#### Influxdb database and user successfully created

#### Running initialization

#### Creating mycodo user
useradd: usuário 'mycodo' já existe
O usuário 'mycodo' já é um membro de 'adm'.
O usuário 'mycodo' já é um membro de 'dialout'.
O usuário 'mycodo' já é um membro de 'gpio'.
O usuário 'mycodo' já é um membro de 'i2c'.
O usuário 'mycodo' já é um membro de 'kmem'.
O usuário 'mycodo' já é um membro de 'video'.
O usuário 'pi' já é um membro de 'mycodo'.
O usuário 'mycodo' já é um membro de 'pi'.

#### Compiling mycodo_wrapper
/home/pi/Mycodo/mycodo/scripts/mycodo_wrapper.c: In function ‘upgrade_commands’:
/home/pi/Mycodo/mycodo/scripts/mycodo_wrapper.c:17:5: warning: ‘strncat’ specified bound 255 equals destination size [-Wstringop-overflow=]
     strncat(full_cmd, "/upgrade_commands.sh ", sizeof(full_cmd));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/Mycodo/mycodo/scripts/mycodo_wrapper.c: In function ‘main’:
/home/pi/Mycodo/mycodo/scripts/mycodo_wrapper.c:35:4: warning: ‘strncat’ specified bound 255 equals destination size [-Wstringop-overflow=]
    strncat(restoreScript, "/upgrade_commands.sh backup-create", sizeof(restoreScript));
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#### Creating symlinks to Mycodo executables

#### Creating files and directories

#### Setting permissions

#### Installing logrotate scripts
Mycodo logrotate script installed

#### Generating SSL certificates at /home/pi/Mycodo/mycodo/mycodo_flask/ssl_certs (replace with your own if desired)
Generating RSA private key, 4096 bit long modulus (2 primes)
..........................................................................................++++
.............................++++
e is 65537 (0x010001)
writing RSA key
Signature ok
subject=O = mycodo, OU = mycodo, CN = mycodo
Getting Private key

#### Disabling installed mycodo startup script
Removed /etc/systemd/system/multi-user.target.wants/mycodo.service.
Removed /etc/systemd/system/mycodo.service.
#### Enabling current mycodo startup script
Created symlink /etc/systemd/system/mycodo.service → /home/pi/Mycodo/install/mycodo.service.
Created symlink /etc/systemd/system/multi-user.target.wants/mycodo.service → /home/pi/Mycodo/install/mycodo.service.

#### Compiling Translations
/home/pi/Mycodo/mycodo/scripts/upgrade_commands.sh: linha 110: /home/pi/Mycodo/env/bin/pybabel: Arquivo ou diretório inexistente

#### Updating Mycodo restart monitor crontab entry
Removing crontab entry ...
Appending to crontab:
-----------------------------------------------
@reboot /var/mycodo-root/env/bin/python /var/mycodo-root/mycodo/scripts/restart_daemon.py --continuouscheck &
-----------------------------------------------
To remove previously added crontab entry, run: /home/pi/Mycodo/install/crontab.sh restart_daemon --remove


#### Running initialization

#### Creating mycodo user
useradd: usuário 'mycodo' já existe
O usuário 'mycodo' já é um membro de 'adm'.
O usuário 'mycodo' já é um membro de 'dialout'.
O usuário 'mycodo' já é um membro de 'gpio'.
O usuário 'mycodo' já é um membro de 'i2c'.
O usuário 'mycodo' já é um membro de 'kmem'.
O usuário 'mycodo' já é um membro de 'video'.
O usuário 'pi' já é um membro de 'mycodo'.
O usuário 'mycodo' já é um membro de 'pi'.

#### Compiling mycodo_wrapper
/home/pi/Mycodo/mycodo/scripts/mycodo_wrapper.c: In function ‘upgrade_commands’:
/home/pi/Mycodo/mycodo/scripts/mycodo_wrapper.c:17:5: warning: ‘strncat’ specified bound 255 equals destination size [-Wstringop-overflow=]
     strncat(full_cmd, "/upgrade_commands.sh ", sizeof(full_cmd));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/Mycodo/mycodo/scripts/mycodo_wrapper.c: In function ‘main’:
/home/pi/Mycodo/mycodo/scripts/mycodo_wrapper.c:35:4: warning: ‘strncat’ specified bound 255 equals destination size [-Wstringop-overflow=]
    strncat(restoreScript, "/upgrade_commands.sh backup-create", sizeof(restoreScript));
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#### Creating symlinks to Mycodo executables

#### Creating files and directories

#### Setting permissions

#### Installing and configuring nginx web server
Removed /etc/systemd/system/mycodoflask.service.
Removed /etc/systemd/system/multi-user.target.wants/mycodoflask.service.
Synchronizing state of nginx.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable nginx
Created symlink /etc/systemd/system/multi-user.target.wants/mycodoflask.service → /home/pi/Mycodo/install/mycodoflask.service.
Created symlink /etc/systemd/system/mycodoflask.service → /home/pi/Mycodo/install/mycodoflask.service.

#### Restarting nginx
#### Restarting mycodoflask

#### Connecting to http://localhost (creates Mycodo database if it doesn't exist)
#### Could not connect to http://localhost. Waiting 60 seconds then trying again (up to 5 times)...
#### Trying again...
#### Could not connect to http://localhost. Waiting 60 seconds then trying again (up to 5 times)...
#### Trying again...
#### Could not connect to http://localhost. Waiting 60 seconds then trying again (up to 5 times)...
#### Trying again...
#### Could not connect to http://localhost. Waiting 60 seconds then trying again (up to 5 times)...
#### Trying again...
#### Could not connect to http://localhost. Waiting 60 seconds then trying again (up to 5 times)...
#### Trying again...
#### Could not connect to http://localhost. Waiting 60 seconds then trying again (up to 5 times)...
#### Trying again...
#### Could not connect to http://localhost. Waiting 60 seconds then trying again (up to 5 times)...
#### Trying again...
#### Could not connect to http://localhost. Waiting 60 seconds then trying again (up to 5 times)...
#### Trying again...
#### Could not connect to http://localhost. Waiting 60 seconds then trying again (up to 5 times)...
#### Trying again...
#### Could not connect to http://localhost. Waiting 60 seconds then trying again (up to 5 times)...
#### Trying again...

#### Setting permissions

#### Restarting the Mycodo daemon
Traceback (most recent call last):
  File "/home/pi/Mycodo/mycodo/scripts/restart_daemon.py", line 12, in <module>
    from mycodo.config import DAEMON_PID_FILE
  File "/home/pi/Mycodo/mycodo/config.py", line 10, in <module>
    from flask_babel import lazy_gettext
ModuleNotFoundError: No module named 'flask_babel'
Job for mycodo.service failed because the control process exited with error code.
See "systemctl status mycodo.service" and "journalctl -xe" for details.
#### Mycodo Installer finished ter jul 21 20:11:11 -03 2020
#### Total install time: 14 minutes and 35 seconds

************************************
** Mycodo successfully installed! **
************************************

The full install log is located at:
/home/pi/Mycodo/install/setup.log

Go to https://192.168.100.31/, or whatever your Raspberry Pi's
IP address is, to create an admin user and log in.

**Comment by kizniche** [comment] 2020-07-22 00:46
This appears to be a duplicate of #787/#792. To fix, run these commands and you should have everything fixed:

```bash
sudo apt remove python-cffi-backend python3-cffi-backend
sudo service mycodo stop
sudo service mycodoflask stop
mv ~/Mycodo/env ~/Mycodo/env-old
sudo /bin/bash ~/Mycodo/mycodo/scripts/upgrade_commands.sh setup-virtualenv
sudo /bin/bash ~/Mycodo/mycodo/scripts/upgrade_commands.sh update-pip3-packages
sudo /bin/bash ~/Mycodo/mycodo/scripts/upgrade_commands.sh update-dependencies
sudo /bin/bash ~/Mycodo/mycodo/scripts/upgrade_commands.sh update-permissions
sudo shutdown now -r
```

**Comment by eliaskill** [comment] 2020-07-22 00:55
thank you so much for the help now it's working !! I even did the loggin :) thanks again

**Comment by eliaskill** [comment] 2020-07-22 00:56
![image](https://user-images.githubusercontent.com/17487151/88121714-f8ef7200-cb9c-11ea-8582-5a2bbd6c8703.png)

**Comment by kizniche** [comment] 2020-07-22 00:58
Glad it was an easy fix. I need to get the next release out soon, as it has the fix to this issue already.

**Comment by eliaskill** [comment] 2020-07-22 01:00
very happy to be able to speak creator of this wonderful tool! pardon my English! I'm Brazilian using a translator!

**Comment by kizniche** [comment] 2020-07-22 01:07
Nice to meet you. I'm sorry you had an issue installing the software. It normally doesn't break so early in its use. haha. Let me know if you find any really bad translation errors with the Portuguese translation. You can change the language to Portuguese on the General Settings page after clicking the gear icon at the top right of the page.

**Closed** 2020-07-23 01:35 UTC
