### ISSUE TITLE
Graph display ignores custom colours

### ISSUE THREAD

**Issue by drgrumpy** [kizniche/Mycodo#760] opened 2020-03-23 16:14 UTC
Version 8.3

Custom colours seem to be ignored and replaced with another colour.

Custom colours checkbox is checked and I select various colours for outputs, pid settings etc.
click save, then some of the colours seem to get changed...
I think it only affects outputs.....(i.e. inputs seem to keep their assigned colours)

**Comment by drgrumpy** [comment] 2020-03-23 16:15
This is in the dashboard.

**Comment by drgrumpy** [comment] 2020-03-23 16:54
See screenshot in #759 where the colours of the outputs are not the same as those that I selected.

**Comment by kizniche** [comment] 2020-03-23 17:14
I can't replicate this behavior. Can you supply a screenshot of both your graph as well as your configuration for that graph?

**Comment by drgrumpy** [comment] 2020-03-23 17:28
This is before saving:
![image](https://user-images.githubusercontent.com/4687649/77344865-b7080980-6d2b-11ea-9a00-108c6dbae6c9.png)

**Comment by drgrumpy** [comment] 2020-03-23 17:34
This is after saving the above colour settings...
![image](https://user-images.githubusercontent.com/4687649/77345004-f20a3d00-6d2b-11ea-9dc8-6f8777c6d995.png)
SSR1 should be red, but has taken the colour above....
Lights is red but should be pale yellow
PWM should be blue but is pale yellow..
I am wondering if there is a for loop that is indexed incorrectly ?

**Comment by drgrumpy** [comment] 2020-03-23 17:47
And if I make a change to another value (like changing data grouping) and save again then I get another change to the colours....
![image](https://user-images.githubusercontent.com/4687649/77346276-e6b81100-6d2d-11ea-9d75-28d14f6b3741.png)

**Comment by kizniche** [comment] 2020-03-23 18:42
I'm not understanding. The screenshots you sent (https://github.com/kizniche/Mycodo/issues/760#issuecomment-602744893 and https://github.com/kizniche/Mycodo/issues/760#issuecomment-602748253) have the correct colors from the configuration matching the graph series.

**Comment by kizniche** [comment] 2020-03-23 18:44
The issue is the ordering. The colors are correctly being applied to the graph series in the exact same order as in the configuration, however PIDs come before Outputs in the configuration and PIDs come after Outputs in the graph series.

**Comment by kizniche** [comment] 2020-03-23 18:53
Fixed the order, now working on another issue: displaying the proper color from the database on the configuration page.

**Comment by kizniche** [comment] 2020-03-23 19:00
Found the last issue and pushed fixes. They'll be available in the next release.

**Comment by drgrumpy** [comment] 2020-03-23 19:02
Great, many thanks.

**Closed** 2020-04-03 01:54 UTC
