### ISSUE TITLE
Error 500 When Attempting to Upgrade Through the Web Interface

### ISSUE THREAD

**Issue by theboyscode** [kizniche/Mycodo#1286] opened 2023-03-20 04:39 UTC
### Describe the problem/bug

Error 500 when trying to upgrade through the web interface.

### Versions:

Version: 8.14.2
Database: 07c7c8ebc195
Model: Raspberry Pi 3 Model B Plus Rev 1.3

Release:
Distributor ID: Debian
Description: Debian GNU/Linux 11 (bullseye)
Release: 11
Codename: bullseye

### Reproducibility

Please list specific setup details that are involved and the steps to reproduce the behavior:

1. Go to Settings 
2.  Click Upgrade
3. I get an Error 500

### Expected behavior

I would expect the update to start

### Additional context

Firmware:
b''

Error (Full Traceback):

Traceback (most recent call last):
  File "/var/mycodo-root/env/lib/python3.9/site-packages/flask_login/utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/esorense/Mycodo/mycodo/mycodo_flask/routes_admin.py", line 534, in admin_upgrade
    current_latest_major_version = current_latest_release.split('.')[0]
AttributeError: 'NoneType' object has no attribute 'split'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/mycodo-root/env/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/mycodo-root/env/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/mycodo-root/env/lib/python3.9/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
  File "/var/mycodo-root/env/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/mycodo-root/env/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/var/mycodo-root/env/lib/python3.9/site-packages/flask_login/utils.py", line 279, in decorated_view
    return func(*args, **kwargs)
  File "/home/esorense/Mycodo/mycodo/mycodo_flask/routes_admin.py", line 534, in admin_upgrade
    current_latest_major_version = current_latest_release.split('.')[0]
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by kizniche** [comment] 2023-03-20 04:41
Duplicate of #1266

Please use the search feature before opening an issue.

**Closed by kizniche** 2023-03-20 04:42 UTC
