### ISSUE TITLE
Upgrade crashing on to Error 500

### ISSUE THREAD

**Issue by enricodina** [kizniche/Mycodo#1274] opened 2023-02-01 13:55 UTC
Version: 8.15.1
Database: 16b28ef31b5b
Model: Raspberry Pi 3 Model B Plus Rev 1.3

Release:
Distributor ID: Debian
Description: Debian GNU/Linux 11 (bullseye)
Release: 11
Codename: bullseye

Firmware:
b''

Error (Full Traceback):

Traceback (most recent call last):
  File "/var/mycodo-root/env/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/mycodo-root/env/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/mycodo-root/env/lib/python3.9/site-packages/flask_restx/api.py", line 675, in error_router
    return original_handler(e)
  File "/var/mycodo-root/env/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/mycodo-root/env/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/var/mycodo-root/env/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/enric/Mycodo/mycodo/mycodo_flask/routes_admin.py", line 514, in admin_upgrade
    current_latest_major_version = current_latest_release.split('.')[0]
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by kizniche** [comment] 2023-02-01 13:56
Duplicate of #1266
Please read the issues before opening a new one.

**Closed by kizniche** 2023-02-01 13:56 UTC

**Comment by enricodina** [comment] 2023-02-01 14:07
Sorry, I though this was a new upgrade, hence a new issue.
Thanks for the hard work
